apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ntopngpack.fullname" . }}-redis
  namespace: {{ include "ntopngpack.namespace" . }}  # Użyj funkcji pomocniczej
  labels:
    {{- include "ntopngpack.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ntopngpack.selectorLabels" . | nindent 6 }}
      app: redis
  template:
    metadata:
      labels:
        {{- include "ntopngpack.selectorLabels" . | nindent 8 }}
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: {{ include "ntopngpack.fullname" . }}-redis-pvc
