apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntopngpack.fullname" . }}-redis-service
  namespace: {{ include "ntopngpack.namespace" . }}  # Użyj funkcji pomocniczej
  labels:
    {{- include "ntopngpack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: {{ .Values.redis.service.portNames.redis }}
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    {{- include "ntopngpack.selectorLabels" . | nindent 4 }}
    app: redis
